### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by Topkek-190** [FastForwardTeam/Server#1]
The repository is empty

**Comment by NotAProton** [comment]
when someone writes it

**Comment by Topkek-190** [comment]
Does the tool depend on the servers of the original extension? Wouldn't that method be unsafe and not guaranteed to work since the original project has been abandoned?

**Comment by NotAProton** [comment]
afaik, yes. A lot of links do need changing

**Comment by Topkek-190** [comment]
Since blank_issues_enabled is disabled in the main repository, I am adding a suggestion here, blank_issues_enabled should be set to true, as there can be issues with the repository, or the code, and setting blank_issues_enabled to false prevents reporting an issue related to either of those

**Comment by NotAProton** [comment]
If we keep blank issues enabled [this](https://github.com/Sainan/Universal-Bypass/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) happens.

There's always the discord for assistance
We can enable discussions if you want.

**Comment by Topkek-190** [comment]
Will it be possible to create a new template for repository issues then? Or to make a different repository for bypass requests?

**Comment by NotAProton** [comment]
I do not know, you should ask that on the discord or @BS-zombie

**Comment by NotAProton** [comment]
I have created a bug report form, you can use that

**Comment by Topkek-190** [comment]
Ok. Closing this issue as the server code hasn't been written yet
